# Generated by Django 5.2.10 on 2026-08-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(blank=True, help_text='Mahsulot/kategoriya/ichki route yoki tashqi havola (ixtiyoriy)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='priority',
            field=models.IntegerField(default=0, help_text="Yuqori raqam = yuqori ustuvorlik (ro'yxatda yuqorida chiqadi)"),
        ),
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('NEWS', 'News'), ('SALE', 'Sale'), ('PROMOTION', 'Promotion'), ('ANNOUNCEMENT', 'Announcement'), ('PRODUCT', 'Product'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
    ]
