# Generated by Django 5.2.10 on 2026-08-28 07:02

from django.db import migrations


def backfill_device_tokens(apps, schema_editor):
    """Profile.device_token (eski, yagona tokenli maydon) da qiymati bor,
    lekin hali DeviceToken yozuvi yo'q profillar uchun DeviceToken yaratadi.

    Faqat QO'SHADI - hech qanday mavjud ma'lumot o'chirilmaydi yoki
    o'zgartirilmaydi. Foydalanuvchi keyingi safar kirganda (login) ham xuddi
    shu backfill LoginView ichida avtomatik ishlaydi - bu migratsiya faqat
    hozirgi vaqtda saqlangan mavjud tokenlar uchun bir martalik "quvib
    yetish" hisoblanadi.
    """
    Profile = apps.get_model("customer", "Profile")
    DeviceToken = apps.get_model("customer", "DeviceToken")

    profiles_with_token = Profile.objects.exclude(device_token__isnull=True).exclude(device_token="")

    created_count = 0
    for profile in profiles_with_token.iterator():
        token = (profile.device_token or "").strip()
        if not token:
            continue
        _, created = DeviceToken.objects.get_or_create(
            token=token,
            defaults={"profile_id": profile.id, "platform": "android", "is_active": True},
        )
        if created:
            created_count += 1

    if created_count:
        print(f"[backfill_device_tokens] {created_count} ta DeviceToken yaratildi (legacy Profile.device_token dan)")


def noop_reverse(apps, schema_editor):
    # Qaytarishda hech narsa o'chirilmaydi (backfill qilingan yozuvlar xavfsiz qoladi).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_devicetoken'),
    ]

    operations = [
        migrations.RunPython(backfill_device_tokens, noop_reverse),
    ]
