# Generated by Django 5.2.10 on 2026-03-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_good_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
