// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgMj9mq-0Au3mGWIMcL2Yo7wuvwVCfGzU',
    appId: '1:677218402440:web:f91b32d2cc8e5ba2e45f3d',
    messagingSenderId: '677218402440',
    projectId: 'millionmart-3d6ba',
    authDomain: 'millionmart-3d6ba.firebaseapp.com',
    storageBucket: 'millionmart-3d6ba.appspot.com',
    measurementId: 'G-EL8H5WMHGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV-tn-5vpARo-Xel4TXtLBikL3UtZGIfk',
    appId: '1:677218402440:android:15b03679094dcbace45f3d',
    messagingSenderId: '677218402440',
    projectId: 'millionmart-3d6ba',
    storageBucket: 'millionmart-3d6ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsVuGa0qppe-7xh8XBOEeYaLaUAQfaEVE',
    appId: '1:677218402440:ios:8d3f457c0664ad1be45f3d',
    messagingSenderId: '677218402440',
    projectId: 'millionmart-3d6ba',
    storageBucket: 'millionmart-3d6ba.appspot.com',
    iosBundleId: 'million.halal.mart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsVuGa0qppe-7xh8XBOEeYaLaUAQfaEVE',
    appId: '1:677218402440:ios:92c746dc5fb4a11be45f3d',
    messagingSenderId: '677218402440',
    projectId: 'millionmart-3d6ba',
    storageBucket: 'millionmart-3d6ba.appspot.com',
    iosBundleId: 'million.halal.mart.RunnerTests',
  );
}
