# Generated by Django 5.2.10 on 2026-02-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='got_from_loyalty',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
