# Generated by Django 5.2.10 on 2026-02-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_order_got_from_loyalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='got_from_loyalty',
        ),
    ]
