# Generated by Django 5.2.10 on 2026-03-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_alter_order_delivery_fee'),
        ('merchant', '0003_remove_order_got_from_loyalty'),
    ]

    operations = [
    ]
