# Generated by Django 5.2.10 on 2026-04-27 05:51

import apps.merchant.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0005_alter_order_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.ForeignKey(blank=True, default=apps.merchant.models.get_default_service, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_delivere_fee', to='merchant.service'),
        ),
    ]
