# Generated by Django 5.2.10 on 2026-08-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0006_alter_order_delivery_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_system_active', models.BooleanField(default=False)),
                ('bonus_amount', models.DecimalField(decimal_places=0, default=500, max_digits=10)),
            ],
        ),
    ]
