# Generated by Django 5.2.10 on 2026-08-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0007_referralsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_step', models.DecimalField(decimal_places=2, default=20, max_digits=10)),
                ('price_per_step', models.DecimalField(decimal_places=0, default=5000, max_digits=10)),
            ],
        ),
    ]
