# Generated by Django 5.2.10 on 2026-08-17 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0008_shippingsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingsettings',
            name='price_per_step',
        ),
        migrations.RemoveField(
            model_name='shippingsettings',
            name='weight_step',
        ),
        migrations.AddField(
            model_name='shippingsettings',
            name='base_fee',
            field=models.DecimalField(decimal_places=0, default=5000, help_text='Har bir 20 kg pochta birligi uchun narx (KRW)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_delivere_fee', to='merchant.service'),
        ),
    ]
