# Generated by Django 5.2.10 on 2026-08-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0009_remove_shippingsettings_price_per_step_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBonusTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=0, help_text="Bo'sh qoldirsangiz - yuqori chegara yo'q", max_digits=12, null=True)),
                ('bonus_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['min_amount'],
            },
        ),
    ]
