# Generated by Django 5.2.10 on 2026-09-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0010_orderbonustier'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, default='', max_length=255)),
                ('chat_ids', models.TextField(blank=True, default='', help_text='Har bir qatorda bitta chat ID (yoki kanal @username)')),
                ('buttons_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
