# Generated by Django 5.2.10 on 2026-09-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0011_telegramsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUpdateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('min_supported_version', models.CharField(blank=True, default='', help_text="Bu versiyadan past bo'lgan ilovalar majburiy yangilanishga yo'naltiriladi (masalan: 1.2.0)", max_length=20)),
                ('latest_version', models.CharField(blank=True, default='', help_text="Eng so'nggi mavjud versiya (ixtiyoriy 'yangilanish mavjud' xabari uchun)", max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('android_store_url', models.URLField(blank=True, default='')),
                ('ios_store_url', models.URLField(blank=True, default='')),
            ],
        ),
    ]
