# Generated by Django 5.2.10 on 2026-09-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0012_appupdatesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsettings',
            name='admin_user_ids',
            field=models.TextField(blank=True, default='', help_text="Buyurtma Qabul qilish/Rad etish tugmalarini bosishga ruxsat etilgan Telegram foydalanuvchi ID'lari, har biri alohida qatorda. Bo'sh qoldirilsa - HAR QANDAY foydalanuvchi bosishi mumkin (eski xatti-harakat, moslik uchun) - haqiqiy himoya uchun shu maydonni to'ldiring."),
        ),
    ]
